CREATE TABLE IF NOT EXISTS CLIENTE(
	ID INT NOT NULL AUTO_INCREMENT,
	NOME VARCHAR(100) NOT NULL,
	IDADE INTEGER,
	SEXO VARCHAR(1) NOT NULL,
	PROFISSAO VARCHAR(30),
	PRIMARY KEY(ID)
);

INSERT INTO CLIENTE(NOME, IDADE, SEXO, PROFISSAO)
	VALUES
		('JHONATAN KOLEN', 21, 'M', 'ESTUDANTE'),
		('DOUGLAS ALVES ', 54, 'M', 'ESTUDANTE'),
		('JHONATAN CESAR', 25, 'M', 'PROGRAMADOR'),
		('LUCAS FISH', 21, 'M', 'ENGENHEIRO');
		
SELECT * FROM CLIENTE;
		
CREATE TABLE CONTA_CORRENTE(
	ID INT NOT NULL AUTO_INCREMENT,
	NUMERO VARCHAR(12) NOT NULL,
	SALDO DECIMAL,
	CODIGO_CLIENTE BIGINT NOT NULL,
	PRIMARY KEY(ID),
	FOREIGN KEY(CODIGO_CLIENTE)
		REFERENCES CLIENTE(ID)
);

INSERT INTO CONTA_CORRENTE(NUMERO, SALDO, CODIGO_CLIENTE)
	VALUES
		(32145, 500.66, 3),
		(31245, 5250.62, 2),
		(3555, 150.54, 1),
		(33345, 550.58, 4);

SELECT * FROM CONTA_CORRENTE;		