CREATE TABLE PACIENTE(
	ID  INTEGER NOT NULL auto_increment,
	NOME VARCHAR(255),
	RG VARCHAR(20),
	CPF VARCHAR(20),
	SEXO VARCHAR(1),	
	RESPONSAVEL_POR INTEGER,
	PRIMARY KEY(id),	
	constraint fk_paciente
	foreign key(RESPONSAVEL_POR) references PACIENTE(id)
);

CREATE TABLE CONTATO(
	ID  INTEGER NOT NULL auto_increment,
	EMAIL VARCHAR(255),
	TELEFONE VARCHAR(20),
	FAX VARCHAR(20),
	CELULAR VARCHAR(20),
	PRIMARY KEY(id)
);

create table PACIENTE_CONTATO(
	PACIENTE_ID INTEGER,
	CONTATO_ID INTEGER,
	PRIMARY key(PACIENTE_ID, CONTATO_ID),
	foreign key(PACIENTE_ID) references PACIENTE(id),
	foreign key(CONTATO_ID) references CONTATO(id)
);

CREATE TABLE ENDERECO(
	ID  INTEGER NOT NULL auto_increment,
	ENDERECO VARCHAR(255),
	CIDADE VARCHAR(255),
	CEP VARCHAR(20),
	BAIRRO VARCHAR(255),
	PRIMARY KEY(id)
);

CREATE TABLE PACIENTE_ENDERECO(
	PACIENTE_ID INTEGER,
	ENDERECO_ID INTEGER,
	PRIMARY KEY(PACIENTE_ID, ENDERECO_ID),
	foreign key(PACIENTE_ID) references PACIENTE(id),
	foreign key(ENDERECO_ID) references ENDERECO(id)
);

CREATE TABLE DENTISTA(
	ID  INTEGER NOT NULL auto_increment,
	CRO VARCHAR(20),
	NOME VARCHAR(255),
	CPF VARCHAR(20),
	PRIMARY KEY(id)
);

create table DENTISTA_CONTATO(
	DENTISTA_ID INTEGER,
	CONTATO_ID INTEGER,
	PRIMARY key(DENTISTA_ID, CONTATO_ID),
	foreign key(DENTISTA_ID) references DENTISTA(id),
	foreign key(CONTATO_ID) references CONTATO(id)
);

CREATE TABLE DENTISTA_ENDERECO(
	DENTISTA_ID INTEGER,
	ENDERECO_ID INTEGER,
	PRIMARY KEY(DENTISTA_ID, ENDERECO_ID),
	foreign key(DENTISTA_ID) references DENTISTA(id),
	foreign key(ENDERECO_ID) references ENDERECO(id)
);

CREATE TABLE CONSULTA(
	ID  INTEGER NOT null auto_increment,
	VALOR DOUBLE,
	DATACRIACAO DATE,
	DENTISTA_ID INTEGER,
	PACIENTE_ID INTEGER,
	PRIMARY KEY(id),
	foreign key(PACIENTE_ID) references PACIENTE(id),
	foreign key(DENTISTA_ID) references DENTISTA(id)
);

CREATE TABLE CONTRATO(
	ID  INTEGER NOT NULL auto_increment,
	PACIENTE_ID INTEGER,
	DENTISTA_ID INTEGER,
	EM_NOME_DO_PACIENTE_ID INTEGER,
	PRIMARY KEY(id),
	foreign key(PACIENTE_ID) references PACIENTE(id),
	foreign key(DENTISTA_ID) references DENTISTA(id),
	foreign key(EM_NOME_DO_PACIENTE_ID) references PACIENTE(id)
);

CREATE TABLE PAGAMENTO(
	ID INTEGER NOT NULL auto_increment,
	CONTRATO_ID INTEGER,
	DATA_PAGAMENTO DATE,
	DATA_VENCIMENTO DATE,
	VALOR DOUBLE,
	JUROS DOUBLE,
	TIPO_JUROS VARCHAR(20),
	PRIMARY KEY(id),
	foreign key(CONTRATO_ID) references CONTRATO(id)
);

CREATE TABLE PROCEDIMENTO(
	ID  INTEGER NOT NULL auto_increment,
	NOME VARCHAR(255),
	DESCRICAO VARCHAR(255),
	DATACRIACAO DATE,
	PRIMARY KEY(id)
);

CREATE TABLE CONSULTA_PROCEDIMENTO(
	CONSULTA_ID INTEGER,
	PROCEDIMENTO_ID INTEGER,
	PRIMARY KEY(CONSULTA_ID, PROCEDIMENTO_ID),
	foreign key(CONSULTA_ID) references CONSULTA(id),
	foreign key(PROCEDIMENTO_ID) references PROCEDIMENTO(id)
);